baseurl = "http://isidoreFarm.com/"
languageCode = "en-us"
title = "Isidore Farm - Lenoir, NC"
themesdir = "themes"
theme = "hugo-phlat-theme"

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    keywords = ["default", "keywords", "if", "no", "front", "matter"]
    description = "A description that will appear as a default if front matter does not exist"
    favicon = "favicon.png"

[social]
    instagram = "https://www.instagram.com/isidorefarm/"

[[menu.header]]
    name = "Home"
    weight = 1
    url = "/"

[[menu.header]]
    name = "Articles"
    weight = 2
    url = "/articles/"

[[menu.header]]
    name = "Gallery"
    weight = 3
    url = "/gallery/"
